version: 2
updates:
    - package-ecosystem: "npm"
      directory: "/"
      schedule:
          interval: "weekly"
    - package-ecosystem: "nuget"
      directory: "/dotnet/"
      schedule:
          interval: "weekly"
      ignore:
        - dependency-name: "System.Collections.Immutable"
          update-types: ["version-update:semver-major"]
