version: 2
updates:
    - package-ecosystem: "npm"
      directory: "/"
      schedule:
          interval: "weekly"
    - package-ecosystem: "nuget"
      directory: "/dotnet/"
      schedule:
          interval: "weekly"
