# MARK: CSS Icons
cssIcons:
    Answer:
        css: |
            width: 20px;
            height: 20px;
        # TODO: add more icons to be added to the css bundle here
definitions:
    # MARK: Icons
    # Ensure order here and from Figma is Size=Default, Boolean=[True|False], Style=Default
    Icon/Answer:
        Size=Default, Stack=False, Style=Default: UhYGuawhIoWxhzQLOu2XCwpBCK8a7p381CWsz/NYaDQ=
        Size=Default, Stack=False, Style=Fill: ZSxm1d0ZixiMrUd53pIsNhbZI6tUJK0o+1T8VtGP8rQ=
        Size=Default, Stack=True, Style=Default: d4gX3H3Sj6dEjtafRAkzrV3FDIshS/FKs2RXdQm5v98=
        Size=Default, Stack=True, Style=Fill: gt10o2xtz6vsbE+Y/HfNU3BEnpVs/J+4EA9OAPHF//s=
    Icon/Arrow:
        Size=Default, Style=Default, Direction=Down: coXzVGYCBzkTNNaUWJH4NUVz4/DpTSAO+/BMOKqjytw=
        Size=Default, Style=Default, Direction=Left: lJ/dusbuhFzN7Cv/8CiQvjqMJ4i4baxkxYnRBo7Qbc0=
        Size=Default, Style=Default, Direction=Right: 7+7cORBbVMC4QAh8QQ7YuNjy9J53GQrJXL8/zNlO5bM=
        Size=Default, Style=Default, Direction=Up: PAEq06HrHwmRpjn2r/VRln2mRtqL28U+6IFfLC/DY88=
    Icon/Award:
        Size=Default, Style=Default: v+2A3J1etrBr9XTqNbQbn+I5/201OAwTRiJTTPAMQ3I=
        Size=Default, Style=Fill: 5pEjI4b1QSKOmDDEWqfu8YOTFH3FheCtaQttxbVVkJo=
    Icon/Bell:
        Size=Default, Style=Default: r09v7rhoycyL/NvCOSeIJFl/0rwc2mzJvbKpv8ZJXFM=
        Size=Default, Style=Fill: ZYWRbdnFjhhfPfhG4HOD/CUWKLLN6zrS1aJvX4sqDcc=
    Icon/Bookmark:
        Size=Default, Style=Default: +AXI3/LDPgztq/O1tlzxPbewDJLC5e+AkHY0r5a50hs=
        Size=Default, Style=Fill: SoilsBkrXfPids6Tnfbl5fNPCBVU/SzX6ZOol1ti54U=
    Icon/Challenge:
        Size=Default, Style=Default: kG3FDOFEQDLmVvnwRmrTf1pYmwOy2FYfdnbEUIP7id0=
        Size=Default, Style=Fill: GageAeDddJSbouE06Xk2hHhrCMX5BwKmDUR7jxTJkkY=
    Icon/Chat:
        Size=Default, Style=Default: UZmhVqgTlqIMTIvKybeETNDkiaep4fk3yffgDe1Z7EQ=
        Size=Default, Style=Fill: mykTtej4DI78wNP2RxJsqiRFaLprEK69nJJG5gBtEMk=
    Icon/Chevron:
        Size=Default, Direction=Down, Style=Default: hgC3wVuvo7pS8ireO0975RvQgDwPJ5uYj45sZoqLS+I=
        Size=Default, Direction=Left, Style=Default: e+FK+EeAtZTY6wtZ5IS2WsUzeRq89lMZ5mFJulgzkI8=
        Size=Default, Direction=Right, Style=Default: RTcj+ktyxhGGhTzyodroDnya/aNOVbPebZTb2UnCjB4=
        Size=Default, Direction=Up, Style=Default: 6HSrg5trhBY70XhYLZyr1HCT+lOw7qsLzD4CbkqkZm4=
    Icon/Community:
        Size=Default, Style=Default: WYsmC7r1uaByLeE7Fe0M/JiaJ/J2kFx9wodtOuHcuaY=
        Size=Default, Style=Fill: 2fELsCJIS7B7KedTN12OZh0fRxP/HZTqeCKmgEDoV1Y=
    Icon/Company:
        Size=Default, Style=Default: F1u/wDLHPBlhJy+0OVOLEDlumvYjJJ2bqV24JPByMaQ=
        Size=Default, Style=Fill: GXotL9LfCMvihXA/cydC9B/kj0dTDaXxGwRZbYXkHuk=
    Icon/Cross:
        Size=Default, Style=Default: oO1a2hCd/XuxAxpZXC+2EXJUAUWKpmv3AwCbkMBdUpQ=
    Icon/Document:
        Size=Default, Style=Default: G4FDvCrT7bv1T8tPFwSIAoiFn64SOcGYKxkZk6/cbIE=
        Size=Default, Style=Fill: tYmTyi2pC1roEjP6XO/qHm//CB7DlHtI1ssoK55G6pQ=
    Icon/Flag:
        Size=Default, Style=Default: VfMyEb3mO3w3SeAp0sJ97ROSLN4daHfESvt0jfRS2ck=
        Size=Default, Style=Fill: 0xduBLtkjETTAxpCLBgrOuEm9lVJjJDlRP2zPalr5iE=
    Icon/Help:
        Size=Default, Style=Default: 2U95Q8KwatUR6bk8cAiooB9waCqSs4e6ttWzS+GfkpM=
        Size=Default, Style=Fill: nBt2DDvfSoHjD1NJjJjMWRxfIku73N0gaQ11N7pEgss=
    Icon/Home:
        Size=Default, Style=Default: PoAKhksimke9mURtwprpur5c1Pdg3DX/JSoQkhpAZoo=
        Size=Default, Style=Fill: Gppd5eUt1tuEUnIbxhRISj+Dh0E3av0J0egRmnfy/yw=
    Icon/Inbox:
        Size=Default, Style=Default: qBx3mL4ty0hIzkEpSaFqrQK9ase5DcjmNg1xOGuPl1M=
        Size=Default, Style=Fill: nEh51bcWsYKvmXcWfvqTGll7UOwJdyDqKjSwKT8XO2I=
    Icon/Jobs:
        Size=Default, Style=Default: ixFJPBGrlypFsCfFb+kmRIR2A/97Py92Lk1/48MCpl4=
        Size=Default, Style=Fill: 56taEheo4mFgkqo0s3fiEo6dGycjNWybjoYuMjfoxOM=
    Icon/Meta:
        Size=Default, Style=Default: aTSbEN8e0F7CiqBBXF31o6FVhi9mwLw4IqFIHejG6jQ=
        Size=Default, Style=Fill: kI6AKct33hBs3ARS42poi1Moio1Go4t9xAvDlAy8fX8=
    Icon/Moderator:
        Size=Default, Style=Default: RtVP3xGnTfC6Nidv0Kns6KmC24OEHOUgDunT5MjbyUM=
        Size=Default, Style=Fill: OmPJ9H/nSSjaqAR1BPkixIvW+1FCrcYBA1oTbZiwhU8=
    Icon/Plus:
        Size=Default, Style=Default: LcnWxFYBuwca1rFC5YzROiVmtTVIBPxXfi73PLxoTp0=
    Icon/Question:
        Size=Default, Stack=False, Style=Default: uJkV1eH3NGwHaRBXUyGawMLauGBECQPD5nU9QbQwA88=
        Size=Default, Stack=False, Style=Fill: MxkrhSkfEU3t2XD9BUGRPwY9SRntZh3AyGUPEEmvAys=
        Size=Default, Stack=True, Style=Default: WTXl6gJ3T+ywl7y/5Pg57ifioeLBhVRydbTW+SnUyxw=
        Size=Default, Stack=True, Style=Fill: SRqL3BBwI4quz/wNah8BvVditzcxAmxzkqjA/+W+Tm0=
    Icon/Search:
        Size=Default, Style=Default: 5tiLt2lGLoDXt/SzUCrvY364PCMpnGWJocLMS4fTvV4=
        Size=Default, Style=Fill: duJJyHlojXunPqpJTroKthlZBk8UwofChzM1QMUzCU4=
    Icon/Settings:
        Size=Default, Style=Default: hXy6zBrXAilwe7PsNqFKPDaag94SCcWhapIiQVLxCQQ=
        Size=Default, Style=Fill: Tfi98jkq7WrjXlqTtPgYaSiXPXJ1VwXzvXpGuU2GWjM=
    Icon/Tag:
        Size=Default, Stack=False, Style=Default: T1klaa7Zj1zxk797T2n0RafV3ukYhe7+Cn1xSv2HrjQ=
        Size=Default, Stack=False, Style=Fill: z/MxNQ3RNBYOHnfxDb5dZI8FEoLxKbVskW+nkjdiF6Y=
        Size=Default, Stack=True, Style=Default: f2A++4TNcT5Q+gu+++yVqfgTQrWZe68TGDCb1C8dNwc=
        Size=Default, Stack=True, Style=Fill: 1FG5l+DlJbDUzYVFwjboijl1nQ2tAWh/JVL259Z9a+U=
    Icon/Trend:
        Size=Default, Direction=Down, Style=Default: daagT7L/UF794p+C2+B/X6LTypAggeTatsb85r6mgXA=
        Size=Default, Direction=Up, Style=Default: eM1sIQVpOBwgxp4zjh7x6uaMEENho5o3T6mMQqL7/cA=
    Icon/User:
        Size=Default, Stack=False: WPgFC7g+cZmTOW/3GY818hRdXDXbzvBUofCt33ZOPpI=
        Size=Default, Stack=False, Style=Fill: D4hdwZDRpdVaomKZSOs77Pkh411K6KcXoUlPKLI77gc=
        Size=Default, Stack=True, Style=Default: p+qDm8bRgfhZyP+A0C4Dqei/Yk6UhXnXfy14Igza0M8=
        Size=Default, Stack=True, Style=Fill: 7e3obtp30vjZIrDFw6KtcJSt0bg5pVQvJAlr5lypv3c=
    Icon/Vote:
        Size=Default, Direction=Down, Style=Default: 9CQL3/zOyLED5v92OSAAni27V02+KhfoNNR/BwHSmiM=
        Size=Default, Direction=Down, Style=Fill: JDB6uLbbq62FIWvOO4kYneQFfzp0MD/B4fVbDi0WeVw=
        Size=Default, Direction=Up, Style=Default: B1kMREGxvjd2HO7xOH9u1rxGzxZsly5jlETcDU93tHs=
        Size=Default, Direction=Up, Style=Fill: dbuluBxCsqn3keaKcPzuea9e+UO5ETFwPvLlSmJw9Gg=
    # MARK: Spots
    Spot/Test: cgbl8iMviW3pIYnKyf1+vyH7e1gsGMlwxzIdPCfD5os=
    # TODO: add more spots here
