// @ts-expect-error types are autogenerated via build script
import * as Icons from "../../dist/icons.js";
// @ts-expect-error types are autogenerated via build script
import * as Spots from "../../dist/spots.js";
import { browserHelper } from "./helpers.js";

export { Icons, Spots, browserHelper };

// automatically run if in the browser and not being imported
if (
    typeof window !== "undefined" &&
    window.document &&
    window.document.currentScript
) {
    browserHelper(
        Icons as Record<string, string>,
        Spots as Record<string, string>
    );
}
