declare module "@stackoverflow/stacks-icons" {
    // @ts-expect-error types are autogenerated via build script
    export * as Icons from "@stackoverflow/stacks-icons/icons";
    // @ts-expect-error types are autogenerated via build script
    export * as Spots from "@stackoverflow/stacks-icons/spots";
}
