// @ts-expect-error types are autogenerated via build script
import * as Icons from "../../dist/icons.js";
// @ts-expect-error types are autogenerated via build script
import * as Spots from "../../dist/spots.js";

export { Icons, Spots };
