name: CI

on:
    push:
        branches: [production]
    pull_request:
        branches: [production]
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Setup node
              uses: actions/setup-node@v3
              with:
                  node-version: "lts/*"

            - name: Install .NET SDK
              uses: actions/setup-dotnet@v3
              with:
                  dotnet-version: "8.0.x" # latest LTS build

            - name: Install npm dependencies
              run: npm ci

            - name: Node Build
              env:
                  FIGMA_ACCESS_TOKEN: ${{ secrets.FIGMA_ACCESS_TOKEN }}
              run: npm run build

            - name: .NET Build
              run: npm run build:nuget

    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Setup node
              uses: actions/setup-node@v3
              with:
                  node-version: "lts/*"

            - name: Install .NET SDK
              uses: actions/setup-dotnet@v3
              with:
                  dotnet-version: "8.0.x" # latest LTS build

            - name: .NET Build
              run: npm run build:nuget
              
            - name: .NET test
              run: npm run test:nuget
